const locationNames = [
  "Uçak",
  "Banka",
  "Plaj",
  "Broadway Tiyatrosu",
  "Kumarhane",
  "Katedral",
  "Sirke",
  "Kurumsal Parti",
  "Haçlı Ordusu",
  "Gündüz Spa",
  "Büyükelçilik",
  "Hastane",
  "Otel",
  "Askeri Üs",
  "Film Stüdyosu",
  "Okyanus Lineri",
  "Yolcu Treni",
  "Korsan Gemisi",
  "Kutup İstasyonu",
  "Polis Karakolu",
  "Restoran",
  "Okul",
  "Servis İstasyonu",
  "Uzay İstasyonu",
  "Denizaltı",
  "Süpermarket",
  "Üniversite",
  "Eğlence Parkı",
  "Sanat Müzesi",
  "Şeker Fabrikası",
  "Kedi Gösterisi",
  "Mezarlık",
  "Kömür Madeni",
  "İnşaat Alanı",
  "Oyun Konvansiyonu",
  "Benzin İstasyonu",
  "Marina",
  "Buz Hokeyi Stadyumu",
  "Cezaevi",
  "Caz Kulübü",
  "Kütüphane",
  "Gece Kulübü",
  "Yarış Pisti",
  "Emekli Ev",
  "Rock Konseri",
  "Tur Otobüsü",
  "Stadyum",
  "Metro",
  "Birleşmiş Milletler",
  "Bağ",
  "Düğün",
  "Hayvanat Bahçesi",
];

export default locationNames;
